---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Get CA cert hash
  delegate_to: "{{ groups['master'][0] }}"
  # https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#token-based-discovery-with-ca-pinning
  shell: |
    openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt |
      openssl rsa -pubin -outform der 2>/dev/null |
      openssl dgst -sha256 -hex |
      awk '{print $2}'
  register: ca_cert_hash
  changed_when: false

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ token }} \
                --discovery-token-ca-cert-hash sha256:{{ca_cert_hash.stdout}} \
                {{ master_ip }}:6443
  register: join_cluster
  notify:
    - Recreate kube-dns
